name: level_survey_app
description: A new Flutter project for level surveying.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.3.4
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  excel: ^4.0.0
  file_saver: ^0.3.1
  share_plus: ^10.0.2
  image_picker: ^1.1.2
  path: ^1.9.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
